// Fill in  your WiFi networks SSID and password
#define SECRET_SSID ""
#define SECRET_PASS ""

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "a2xn1ay8x8kinj-ats.iot.ap-southeast-2.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIIChjCCAW6gAwIBAgIULcwX92F97n+ifZK4Y0N+gNRg8a4wDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTI0MDQxMjA2MTcz
NFoXDTQ5MTIzMTIzNTk1OVowFjEUMBIGA1UEAxMLbWtyd2lmaTEwMTAwWTATBgcq
hkjOPQIBBggqhkjOPQMBBwNCAASlGOtnGeMCPgeaKSTGqGbmTWnVr9G3C0PqO433
N66DU32zzJKaSPO+AlY8jQipKP15UkXLBxMRH/nU6ytkE3/ao2AwXjAfBgNVHSME
GDAWgBSvL9FEykyE8Kp6ihiIeiJTr5g+JzAdBgNVHQ4EFgQUoIGny/BnCr2awGrb
UbsVAniSzI8wDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZIhvcN
AQELBQADggEBADIR6EKtlDrv3mN/Wfpg9p64kh4KCLs118szToy4t0zr4FJBR/TT
FHjIXt/GnRxlXJ2C/2n/KCeoCGwimmBQ7E/Sn2I3Uhm6lxqi1o4ke6/6HMk/GlnZ
l+FdkiEBUXEEVEA6/KyzsLYBBQF0/hU63PxQ1Jm0V1MIYEOkBCBBJQ5P866/bArf
hzrJ07rAPKlqWaf1jrvxNOGhVlAaeDLOtqi/JUjHBKrW1Qsyg6rrS8qXVFkgL8CF
lG1rAwcSbcGaJF04dyK85YhSrxvyzPjJQ2Fdv96YUHNEIhCXHTHo5Wgrk0mz2heK
IsMPf/+Ro/sGewR7muwoJn4oK/NcyHxzt0k=
-----END CERTIFICATE-----
)";